spring.application.name=playlist-api

# configuracao do banco H2
spring.datasource.url=jdbc:h2:mem:playlistdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Segue a URL para validação - http://localhost:8080/h2-console / obs: não pode ter nada na porta 8080

# A tela do spring security



#função para ver as tabelas pelo navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


spring.jpa.hibernate.ddl-auto=update

# mostra o sql que o hibernate ta rodando
spring.jpa.show-sql=true